### PR TITLE
Update ApodiniMigration to ApodiniMigrator 0.2.0; bump ApodiniTypeInformation to 0.3.0

### PR DESCRIPTION
**Pull request by bauer-andreas**
# Update ApodiniMigration to ApodiniMigrator 0.2.0; bump ApodiniTypeInformation to 0.3.0

## :recycle: Current situation & Problem

Currently Apodini runs with `ApodiniMigrator` `0.1.x` and `ApodiniTypeInformation` `0.2.x`.

## :bulb: Proposed solution

This PR updates the code base and bumps both dependencies to their latest version, ApodiniMigrator to [0.2.0](https://github.com/Apodini/ApodiniMigrator/releases/tag/0.2.0) and ApodiniTypeInformation to [0.3.0](https://github.com/Apodini/ApodiniTypeInformation/releases/tag/0.3.0).

## :gear: Release Notes 
* Updated `ApodiniMigrator` to [0.2.0](https://github.com/Apodini/ApodiniMigrator/releases/tag/0.2.0)
* Updated `ApodiniTypeInformation` to [0.3.0](https://github.com/Apodini/ApodiniTypeInformation/releases/tag/0.3.0)

### Related PRs
-- 

### Testing
--

### Reviewer Nudging
--

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/Apodini/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Apodini/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/Apodini/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/Apodini/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bauer-andreas** [comment]
Anybody got an idea why the LoggerTests are failing:

```
/Users/runner/work/Apodini/Apodini/Tests/ApodiniObserveTests/ApodiniLoggerTests.swift:762: error: -[ApodiniObserveTests.ApodiniLoggerTests testServiceSideStreamingPattern] : XCTAssertEqual failed: ("1") is not equal to ("2")
9003
/Users/runner/work/Apodini/Apodini/Tests/ApodiniObserveTests/ApodiniLoggerTests.swift:848: error: -[ApodiniObserveTests.ApodiniLoggerTests testServiceSideStreamingPattern] : XCTAssertEqual failed: ("1") is not equal to ("2")
```

Doesn't seem to be a one-off thing.

**Comment by PSchmiedmayer** [comment]
@Supereg My first guess would be the regression we discussed in https://github.com/Apodini/Apodini/pull/374#issuecomment-993561055 ... I see that your Package.resolved file reduced the versions of some dependencies. Maybe running a `swift package update` for the main package and the test web service might resolve the issue.
Maybe we should add the latest version of the responsible NIO-related packages to the `from: ...` clauses in the Package.swift file to ensure that we don't have such regressions in the future.

**Review by PSchmiedmayer — APPROVED** [review]
@Supereg Apart from the failing tests and the reduced Swift Package dependency versions I noted in a comment above the PR looks good to me 👍

**Comment by philippzagar** [comment]
> ApodiniLoggerTests

I took a closer look into it, this topic strongly correlates to my comments in PR #374. 
Just had to update the package versions as the newer NIO version apparently kicked out the `content-length` attribute of a request if it is 0.

**Review by philippzagar — APPROVED** [review]
Nice PR! I just fixed the test cases regarding `ApodiniObserve` by updating to the latest package versions, didn't take a closer look at the rest of the PR 👍

**Comment by bauer-andreas** [comment]
thanks a lot @philippzagar for directly resolving the issue 🚀
